site_name: Contracts
repo_url: https://github.com/systopia/de.systopia.contract
theme: material

pages:
- Home: index.md
- 'Contract types': contract-types.md
- 'Contract modifications': contract-modifications.md

markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite
- toc:
    permalink: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tilde
- pymdownx.betterem
- pymdownx.mark
